### ISSUE TITLE
Updated report

### ISSUE THREAD

**Issue by KST0NE** [KST0NE/Assignment-6#1]
Updated report with YAML, equations, and references. Also added headers and footers to the pages and a table of contents.

I actually do have a real issue in that I got my references working and subsequently it all stopped working. I've been googling and trying things for too long at this point and am hoping you'll have the solution! I cannot get the references/second in text citation to work. I have tried using both the DOI method as well as creating a .bib file from Zotero with the references. 

This repo has the DOI version which is at least letting me knit the first reference.

**Comment by mdscheuerell** [comment]
I'm sorry about the Marwick reference, but you did a nice job of working through the problem. Also, FYI, your date format is not quite right. See the key [here](https://fish549.github.io/website/homework/week_06/hw_06_publishing_key.html).
